실험명: 실험명
seed: 42
retrieval_name: SparseTFIDF
retrieval_fuzz: True
retrieval_list:
  SparseTFIDF: SparseTFIDF
colbert_model_name:
model:
  model_name: klue/bert-base
  num_attention_heads: 12
  attention_probs_dropout_prob: 0.1
  num_hidden_layers: 12
  hidden_dropout_prob: 0.1
  option: # question_masking, cnn, both, original
  select_option: 
    question_masking: AutoModelForQuestionAnsweringAndMLM
    cnn: AutoModelForQuestionAnsweringAndCNN
    original: AutoModelForQuestionAnswering
  pretrain: # None, korquad_1.0.csv, aug_v1.csv, aug_v2.csv
tokenizer:
  max_seq_length: 384
  pad_to_max_length: False
  doc_stride: 128
  max_answer_length: 30
option:
  overwrite_cache: False
  eval_retrieval: True
  num_clusters: 64
  top_k_retrieval: 10
  use_faiss: False
  batch_size: 8
  use_fuzz: False
wandb:
  id: gibum1228
  project: MRC